baseURL = "https://u1tnk.github.io/"
languageCode = "ja-jp"
title = "u1tnk.log"
theme = "PaperMod"
enableEmoji = true

[permalinks]
  post = "/blog/:year/:month/:day/:filename/"

[params]
  sidebarMenuEnabled = false

  author = "u1tnk"

  rss = false

  compactIndex = true

  googleAnalytics = "UA-2532590-5"

  dateFormat = "2006/01/02"

  disableReadingTime = true

  customCSS = ["css/custom.css"]

[[menu.main]]
  Name = "posts"
  URL = "/"
  weight = -5

[[menu.main]]
  Name = "about"
  URL = "/about"
  weight = -4

[[menu.main]]
  Name = "rss"
  URL = "/atom.xml"
  weight = -3

[outputFormats.RSS]
  baseName = "atom"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
